CREATE TABLE CUSTOMER(
    ID CHAR(36) PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL UNIQUE,
    PHONE VARCHAR(15) NOT NULL UNIQUE,
    EMAIL VARCHAR(100) NOT NULL UNIQUE,
    DOCUMENT VARCHAR(14) NOT NULL UNIQUE,
    TYPE VARCHAR(20) NOT NULL
)