CREATE TABLE SERVICE_ORDER(
    ID CHAR(36) PRIMARY KEY,
    ENTRY_DATE DATE NOT NULL,
    ESTIMATED_DELIVERY_DATE DATE NOT NULL,
    DEFECT VARCHAR(255) NOT NULL,
    EXIT_DATE DATE,
    STATUS VARCHAR(100) NOT NULL,
    PRIORITY INT NOT NULL,
    NOTES VARCHAR(255),
    PRICE DECIMAL(10, 2) NOT NULL,
    TECHNICIAN_ID CHAR(36) NOT NULL,
    EQUIPMENT_ID CHAR(36) NOT NULL,
    CUSTOMER_ID CHAR(36) NOT NULL,
    CONSTRAINT FK_TECHNICIAN FOREIGN KEY (TECHNICIAN_ID) REFERENCES TECHNICIAN(ID),
    CONSTRAINT FK_EQUIPMENT FOREIGN KEY (EQUIPMENT_ID) REFERENCES EQUIPMENT(ID),
    CONSTRAINT FK_CUSTOMER FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(ID)
)