CREATE TABLE SERVICE_ORDER_SERVICE(
    SERVICE_ORDER_ID CHAR(36) NOT NULL,
    SERVICE_ID CHAR(36) NOT NULL,
    CONSTRAINT FK_SERVICE_ORDER FOREIGN KEY (SERVICE_ORDER_ID) REFERENCES SERVICE_ORDER(ID),
    CONSTRAINT FK_SERVICE FOREIGN KEY (SERVICE_ID) REFERENCES SERVICE(ID)
)